### ISSUE TITLE
Weird Maximum call stack size Exceeded error

### ISSUE THREAD

**Issue by Taconvino** [uhlryk/angular-dynamic-number#31]
Hello,

I'm getting thiss error:

angular.js:10046 RangeError: Maximum call stack size exceeded
    at forEach (http://localhost:49300/scripts/angular.js:325:18)
    at $setViewValue (http://localhost:49300/scripts/angular.js:17681:5)
    at changeViewValue (http://localhost:49300/scripts/dynamic-number.js:191:27)
    at directiveParser (http://localhost:49300/scripts/dynamic-number.js:444:13)
    at http://localhost:49300/scripts/dynamic-number.js:587:48
    at http://localhost:49300/scripts/angular.js:17682:15
    at forEach (http://localhost:49300/scripts/angular.js:325:18)
    at $setViewValue (http://localhost:49300/scripts/angular.js:17681:5)
    at changeViewValue (http://localhost:49300/scripts/dynamic-number.js:191:27)
    at directiveParser (http://localhost:49300/scripts/dynamic-number.js:444:13) undefined

I tried the library in a simple Angular application (with no other stuff in it) and it works as expected, so this is probably a configuration problem in my own application.  The thing is, I have no idea where to start looking.  I'm using the HotTowel Angular template, if that makes any difference.

**Comment by Taconvino** [comment]
Never mind.  It was an AngularJS version problem on my part.
